### ISSUE TITLE
Crash when clicking on "Normal Items"

### ISSUE THREAD

**Issue by andersosthus** [anoutsider/advanced-logistics-system#1]
Hi,

Getting the following error when clicking on the "Normal Items" button:
`Error while running the event handler: __advanced-logistics-system__/control.lua:597: LuaEntity API call when LuaEntity was invalid.`

Running ALS 0.2.2

**Comment by anoutsider** [comment]
Are you using any other mods that add new types of chests?

**Comment by andersosthus** [comment]
Hi, yes, I'm using [Long's Large Chests Mod](http://www.factorioforums.com/forum/viewtopic.php?f=94&t=13312). That should be the only mod that adds chests.

**Comment by anoutsider** [comment]
ok so this is related to the other issue you posted, is the chest you are trying to view on issue #2 one of these chests?

i will be looking into that mod's code and will hopefully be pushing a compatibility fix soon.

**Comment by andersosthus** [comment]
No, I don't have any of those chests placed in this game at all, I just have the mod installed.

**Comment by anoutsider** [comment]
Version 0.2.3 fixed the issue
