### ISSUE TITLE
[META] Releases aren't being displayed on GitHub

### ISSUE THREAD

**Issue by JyeGuru** [anoutsider/advanced-logistics-system#10]
Currently the update process for the mod for me is:
- See Github Repo in "Starred" list (or get notified by RSS/etc)
- Click forum link in Readme
- Download from forums

This means it's not possible for me to download at work (unless I just dump the repo source) and I can't use my normal notification method for new project releases.

_This is entirely a personal issue, and understand if you won't change this, however it would be much more convenient for those that have a lot of mods and don't scan the forums regularly for update posts_

**Comment by anoutsider** [comment]
I didn't realize people were actually using github to download and the reason i stopped issuing releases here, is that Github started appending the repository name to my tags, so the filename would end up looking like this "advanced-logistics-system-advanced-logistics-system_0.2.13" which doesn't work..

The alternative was to actually upload the release file myself when drafting a new release, which i just went ahead and did for all the missing releases, i'll make sure to keep it up whenever a new version is released as well :)

**Comment by JyeGuru** [comment]
That makes sense. I believe it's possible to manually attach the zip to the release with whichever name you want, if that helps?

**Comment by anoutsider** [comment]
Yes which is what i did for the missing releases, and will do for the upcoming ones.
