### ISSUE TITLE
Server crashes with error nil in a table

### ISSUE THREAD

**Issue by Demosthenexx** [anoutsider/advanced-logistics-system#11]
We tried to place a roboport prior to any logistics chests, and got an error for line 816 regarding nil value.

https://github.com/anoutsider/advanced-logistics-system/blob/master/control.lua#L816

I'm trying to see if we place a chest if it fixes the error.

**Comment by Demosthenexx** [comment]
I confirmed that once we made and placed a storage chest, the error stopped. We have not yet researched the ALS tech yet.

**Comment by anoutsider** [comment]
Thank you for the report, clearly missing an "if diconnected ~= nil" sanity check there, i thought i covered all these in a previous release but apparently i missed some :)

**Comment by anoutsider** [comment]
Fixed in recent releases
