### ISSUE TITLE
Escape key doesn't close GUI

### ISSUE THREAD

**Issue by jakimfett** [anoutsider/advanced-logistics-system#13]
When the Advanced Logistics System GUI is active, I would expect the "Escape" key to close the GUI like it does for most of the other GUIs in the game. 

Currently, pressing the "Escape" key opens the game menu over top of the ALS GUI.

Tested with Factorio v0.12.35 and ALS v0.2.13 without any other mods.

![](http://pics.jakimfett.com/2016-06-28_23-05-17.png)

**Comment by jocker-il** [comment]
isn't this as easy as adding the "escape key pressed" to "mod icon in gui pressed" ?

 something like `_on_click ("escape_key") do_` & call the `close_gui` function used for `_on_click ("mod_gui_icon")`

**Comment by anoutsider** [comment]
This functionality was added on the 0.3.x release, however the ESC key doesn't really work, there are 2 alternatives now.. using "L" to toggle the GUI on/off and also using another key combination to just close it, the default for this is "Shift + ESC", this one is setup to override default game behavior for shortcuts, so i'd be careful setting it to a key that you normally use.

Both are customisable from the game options
