### ISSUE TITLE
Item search not updating

### ISSUE THREAD

**Issue by jakimfett** [anoutsider/advanced-logistics-system#14]
When searching for items in Advanced Logistics System v0.12.12+, the list of items does not update.

I tried typing into the search field and waiting several seconds. I also tried pressing the "Enter" key. I also tried going to the "Settings" tab and clicking the "Update Logistic Data" button. I tried variations on search terms, eg uppercase/lowercase and partial words.

Tried v0.12.12 and v0.12.13 with Factorio v0.12.35 without any other mods.

![](http://pics.jakimfett.com/2016-06-28_23-10-11.png)

**Comment by anoutsider** [comment]
I doubt anyone is still using 0.12 at this point, i just pushed an update for 0.13 that adds alot of new features and fixes most of the old bugs, and probably introduces new ones..

Please test it out and let me know if this is still an issue.
