### ISSUE TITLE
locales updated (on-going)

### ISSUE THREAD

**Issue by jocker-il** [anoutsider/advanced-logistics-system#15]
Hi,

 This is for you (@anoutsider) to update translators if & when new string are added so we can know to update the locale files :)

that's how we do it on @narc0tiq's [EvoGUI](https://github.com/narc0tiq/evoGUI/issues/23)

**Comment by anoutsider** [comment]
Hi,
Thanks for this, here is the the recent locale updates for the new version

https://github.com/anoutsider/advanced-logistics-system/commit/12150d9115a1806676add0d614d261d9ab2ca4b7#diff-60b1d52cd5cd51c4c37402c122f3d6dcR28

**Comment by jocker-il** [comment]
Might I suggest that in the future, you only mention issue #15 (like that) when you commit, comment or merge, so there is a reference from it to this issue and anyone can check it out

 The link you put here sent me to the actual changes  (all of them) and that's not information I can use.

**Comment by anoutsider** [comment]
Normally i never made individual commits, since no one else was contributing to the project, and i just used get for tracking/tagging releases. but since people seem to be interested in contributing, i'll be making sure i do individual feature commits from now on.

The link i gave you should take you to the local cfg file changes in the 0.3 release, not sure why you can't use it?

**Comment by jocker-il** [comment]
The link actually shows all the changes made in that commit and it's not necessary for me. All I need to know is that you made a change in locale files and that I should Review the files and translate new text. 

 That said, however you choose to inform me  (And other translators) about changes, is ok. I just made a suggestion for your consideration. 

 Thank you for developing advanced-logistics-system - I  like it. :)

Sent from Samsung Mobile.

<div>-------- Original message --------</div><div>From: Amr Abed notifications@github.com </div><div>Date:22/08/2016  20:42  (GMT+02:00) </div><div>To: anoutsider/advanced-logistics-system advanced-logistics-system@noreply.github.com </div><div>Cc: "The JoCKeR (IL)" jockeril@yahoo.com, State change state_change@noreply.github.com </div><div>Subject: Re: [anoutsider/advanced-logistics-system] locales updated (on-going)
  (#15) </div><div>
</div>Normally i never made individual commits, since no one else was contributing to the project, and i just used get for tracking/tagging releases. but since people seem to be interested in contributing, i'll be making sure i do individual feature commits from now on.

The link i gave you should take you to the local cfg file changes in the 0.3 release, not sure why you can't use it?

**Comment by anoutsider** [comment]
That is strange, the link i posted takes me to the local.cfg changes, the page has all the other changes but it should scroll you to where the translation file changes/additions are.

Anyway, from now on i'll make sure to add these in separate commits.

**Comment by jocker-il** [comment]
No more Hebrew in Factorio
