### ISSUE TITLE
Crash when clicking the info icon on a logistic chest in ALS.

### ISSUE THREAD

**Issue by andersosthus** [anoutsider/advanced-logistics-system#2]
Hi,

When I click on that "search icon" in the View column, I get the following crash:
`Error while running the event handler: __advanced-logistics-system__/control.lua:638: LuaEntity API call when LuaEntity was invalid.`

Running ALS 0.2.2

**Comment by anoutsider** [comment]
This seems to trigger because the chest doesn't exist anymore, but it shouldn't since the chests are removed from the internal lists when they are deconstructed or destroyed.

does the chest still exist? is it a normal chest or a modded one?

**Comment by andersosthus** [comment]
It happends on any chest I try with. Only normal chests (Logistic chests and steel chests).

**Comment by anoutsider** [comment]
Version 0.2.3 fixed the issue
