### ISSUE TITLE
Freezing while deconstructing roboports on big bot based map

### ISSUE THREAD

**Issue by Danielv123** [anoutsider/advanced-logistics-system#3]
I have a big map (14 mb) completelly bot based. Whenever I try to remove one of my roboports, no matter if it is connected to a network or not, it freezes for 5-10 seconds. I have tried removing other mods and this mod ended up being the problem. Using version 0.2.4

**Comment by anoutsider** [comment]
it's probably the disconnected chests check loop that is causing it, would it be possible for you to send me the save?

i'd like to run some test and hopefully a fix.

**Comment by Danielv123** [comment]
Uploading now with all the mods I am using included. Game dies if removing some of them, but you should be able to figure it out. Save name is `moded-economy.zip`

Edit: added link: https://mega.nz/#!1c81kLbZ!FTd_bIvVxDz9-9nW1x_PLzWGaIpggH0X8yAlx9jv8Fk
This upload is without waitex as it shouldn't have any impact on gameplay.

**Comment by Rseding91** [comment]
Just an FYI: you can drastically improve the performance (and simplicity of the code) on all aspects by using the new LogisticNetwork and LogisticCell interfaces added recently:

http://www.factorioforums.com/wiki/index.php?title=Lua/LogisticNetwork
http://www.factorioforums.com/wiki/index.php?title=Lua/LogisticCell

**Comment by anoutsider** [comment]
@Rseding91 Wow this is amazing! i was knee deep working on a sweep line algorithm to better calculate the network.. and it's been tough :)

This is a life saver, thank you for pointing it out and for the awesome work on the api.

**Comment by anoutsider** [comment]
Latest release 0.2.6 should fix your issue, personally tested it with your save and seems to be running smoothly.
- sorry for the delay

**Comment by Danielv123** [comment]
Thanks for fixing it, delay won't be a problem as I can't start playing again before december.
