### ISSUE TITLE
Effects not showing

### ISSUE THREAD

**Issue by uduse** [anoutsider/advanced-logistics-system#37]
Hi there,

I am not sure if I am doing something wrong but the research gives me nothing (no new craftable item shows up after researching). I am on 0.14.21.

![image](https://cloud.githubusercontent.com/assets/4717005/20865035/6f5d4932-b9bb-11e6-94e4-ec86866e839d.png)

**Comment by Thynix** [comment]
I was similarly confused - it adds an icon in the upper left that looks like ![this](https://raw.githubusercontent.com/anoutsider/advanced-logistics-system/master/graphics/icons/advanced-logistics-system.png) that you click on to open the menu. I should probably submit a pull request that mentions that in the readme.

**Comment by uduse** [comment]
Closed due to inactivity.
