### ISSUE TITLE
Searching networks with upper case characters fails

### ISSUE THREAD

**Issue by crosma** [anoutsider/advanced-logistics-system#9]
For example, if you search for a word with upper case characters such as "Coal", it does not match. If you search for "coal" it works fine.

**Comment by anoutsider** [comment]
Thanks for the report,

The search is tricky because it's compared against the items identifiers not the "Localized Strings" but it should be case insensitive.

I'll have a look, and see if this can be fixed.

**Comment by Danielv123** [comment]
If this is still an issue, how about something LUA equivalent to input.toLowerCase()?

**Comment by anoutsider** [comment]
This has been fixed in the latest 0.3.0 release for factorio 0.13
